version: 1.0.{build}
image:
- Ubuntu

environment:
  global:
    USER: sumankhanal
  matrix:
    - IMAGE: rakurstudio
    - IMAGE: rustrakurstudio
    - IMAGE: swig-python-boost

build_script:
  - ps: ./build.ps1

deploy_script:
  - ps: ./deploy.ps1